name: Build Android APK

on:
  push:
    tags:
      - 'latest'  # Example: v1.0, v2.2.1
  workflow_dispatch:  # 👈 Manual trigger support

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}

      - name: Generate version name
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION_NAME="${{ github.event.release.tag_name }}"
          else
            VERSION_NAME="dev-$(date +'%Y%m%d')-${{ github.sha }}"
          fi
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "::set-output name=name::$VERSION_NAME"        

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease -PversionName=${{ env.VERSION_NAME }}

      - name: Upload APK to GitHub Release (if tagged release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
